Calculate LeaderBoard
kousikr26/darkforest-deploy pull request #1
Opened 2022-08-05 08:59 UTC by Harsh8196

LeaderBoard Calculation on Frontend side.

2022-08-07 17:01 UTC, kousikr26 requested changes

2022-08-07 17:01 UTC, kousikr26 commented on packages/hashing/package.json
> -    "prepare": "tsc -p . && cp -r src/fractions dist/fractions",
I assume this was changed to work with your local windows machine? Please revert to this before making a pr as the netlify instance is linux based

2022-08-07 17:01 UTC, kousikr26 commented on client/.env
> +NODE_ENV = production
Please add the .env file in the gitignore as well

2022-08-08 03:30 UTC, Harsh8196 commented on packages/hashing/package.json
> -    "prepare": "tsc -p . && cp -r src/fractions dist/fractions",
Yes, Correct. I'll revert back to those changes.

2022-08-08 03:37 UTC, closed without merging